package res

import (
	_ "image/png"

	"github.com/explodes/go-wo"
	"github.com/faiface/pixel"
)

// Load is an alias for Asset. Some IDEs (cough intellij)
// do not support large go files generated by bin-data
func Load(path string) ([]byte, error) {
	return Asset(path)
}

func NewPic(path string) (*pixel.PictureData, error) {
	bytes, err := Load(path)
	if err != nil {
		return nil, err
	}
	return wo.DecodePicture(bytes)
}
